version: "3"

services:

  test_runner:
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore-test
      - BITCORE_CONFIG_PATH=/bitcore/bitcore.config.json
    command: npm run node
    depends_on:
      - db
      - bitcoin
#      - parity
#      - rippled

  db:
    image: mongo

  bitcoin:
    image: ruimarinho/bitcoin-core:0.18
    ports:
      - "18443:18443"
      - "18444:18444"
      #      - "8332:8332"
      #      - "8333:8333"
    command:
      -printtoconsole
      -regtest=1
      -server=1
      -txindex=1
      -rpcallowip=172.0.0.0/24
      -rpcbind=0.0.0.0
      -rpcuser=realiotest
      -rpcpassword=s1gmQdsNifs6K55eTZSLmSKw2qxs4CV0MV7nS2A5Q90=

#  parity:
#    image: parity/parity:v2.4.6
#    ports:
#      - "8545:8545"
#      - "8546:8546"
#    volumes:
#      - ./.docker/parity-password:/data/pw
#    command:
#      --config=dev
#      --jsonrpc-interface=0.0.0.0
#      --ws-interface=0.0.0.0
#      --ws-port=8546
#      --jsonrpc-apis=all
#      --ws-apis=all
#      --unlock 00a329c0648769a73afac7f9381e08fb43dbea72
#      --password /data/pw

#  rippled:
#    build:
#      context: ""
#      dockerfile: .docker/rippled.Dockerfile

  insight:
    build:
      context: ./packages/insight
      dockerfile: ./packages/insight/Dockerfile
    links:
      - bitcore-node
    environment:
      - API_URL=bitcore-node

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
